name: Deploy `pre-signup` Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - skip

jobs:
  deploy:
    name: Check
    uses: postech-5soat-grupo-25/tech-challenge-templates/.github/workflows/deploy-lambda.yml@main
    secrets:
      script: deploy-pre-signup.sh
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
